Repository i-on-project/web, pull requests merged in 2021-07, with the labels that each got.

#59 Fix on usage of refresh token
  project/business-logic-layer/i-on-web-auth.js
  project/data-access-layer/core-data.js
  project/data-access-layer/i-on-web-db-elastic.js
  project/i-on-web-server.js
  project/presentation-layer/i-on-web-auth-api.js
  project/presentation-layer/i-on-web-ui.js
Labels: bug, high priority, integrated mode

#63 Review/services
  project/__tests__/test-i-on-web.js
  project/business-logic-layer/i-on-web-auth.js
  project/business-logic-layer/i-on-web-services.js
  project/data-access-layer/i-on-web-db-elastic.js
  project/data-access-layer/mock-data.js
  project/i-on-web-server.js
  project/mock-data/integrated/current_calendar_term.json
  project/presentation-layer/i-on-web-ui.js
  project/test/test-services.js
  project/views/class-sections.hbs
  project/views/home.hbs
  project/views/programme.hbs
  project/views/programmeOffers.hbs
  project/views/user-classes.hbs
  project/views/user-profile.hbs
Labels: enhancement, refactor

#66 Enhancement/calendar term
  project/business-logic-layer/i-on-web-auth.js
  project/business-logic-layer/i-on-web-services.js
  project/business-logic-layer/remove-metadata.js
  project/cache/i-on-web-cache.js
  project/data-access-layer/core-data.js
  project/data-access-layer/core-decorators/core-add-missing-data.js
  project/data-access-layer/core-decorators/core-data-transformer.js
  project/data-access-layer/i-on-web-db-elastic.js
  project/data-access-layer/mock-data.js
  project/i-on-web-server.js
  project/mock-data/integrated/auth/authenticationMethodsAndFeatures.json
  project/mock-data/integrated/calendarTerms/1718i/1/events.json
  project/mock-data/integrated/calendarTerms/1718i/semester_calendar.json
  project/mock-data/integrated/calendarTerms/1718v/1/class.json
  project/mock-data/integrated/calendarTerms/1718v/1/classSections/1D.json
  project/mock-data/integrated/calendarTerms/1718v/1/events.json
  project/mock-data/integrated/calendarTerms/1718v/2/class.json
  project/mock-data/integrated/calendarTerms/1718v/3/class.json
  project/mock-data/integrated/calendarTerms/2020-2021-2/1/class.json
  project/mock-data/integrated/calendarTerms/2020-2021-2/1/classSections/1D.json
  project/mock-data/integrated/calendarTerms/2020-2021-2/1/events.json
  project/mock-data/integrated/calendarTerms/2020-2021-2/2/class.json
  project/mock-data/integrated/calendarTerms/2020-2021-2/3/class.json
  project/mock-data/integrated/calendarTerms/2020-2021-2/semester_calendar.json
  project/mock-data/integrated/calendarTerms/2021v/1/class.json
  project/mock-data/integrated/calendarTerms/2021v/1/classSections/1D.json
  project/mock-data/integrated/calendarTerms/2021v/2/class.json
  project/mock-data/integrated/calendarTerms/2021v/3/class.json
  project/mock-data/integrated/calendarTerms/2021v/semester_calendar.json
  project/mock-data/integrated/current_calendar_term.json
  project/mock-data/integrated/user-courses/1.json
  project/mock-data/standalone/current_calendar_term.json
  project/package-lock.json
  project/package.json
  project/presentation-layer/i-on-web-ui.js
  project/test/test-services.js
Labels: enhancement, integrated mode

#67 Improvements/user interface
  project/static-files/css/common.css
  project/static-files/css/schedule.css
  project/views/home.hbs
  project/views/programmeOffers.hbs
  project/views/user-schedule.hbs
Labels: enhancement, user interface

#69 Enhancement/prefix env variable
  .docker/docker-compose-heroku.yml
  project/business-logic-layer/i-on-web-services.js
  project/i-on-web-server.js
  project/presentation-layer/i-on-web-ui.js
  project/static-files/css/calendar.css
  project/static-files/css/master.css
  project/views/about.hbs
  project/views/class-sections.hbs
  project/views/home.hbs
  project/views/layout.hbs
  project/views/login.hbs
  project/views/programme.hbs
  project/views/programmeOffers.hbs
  project/views/user-calendar.hbs
  project/views/user-classes.hbs
  project/views/user-profile.hbs
Labels: enhancement

#70 Review and fixes
  project/data-access-layer/cache/cache.js
  project/data-access-layer/elasticsearch/i-on-web-db-elastic.js
  project/data-access-layer/integrated/core-add-missing-data.js
  project/data-access-layer/integrated/core-cache.js
  project/data-access-layer/integrated/core-data-transformer.js
  project/data-access-layer/integrated/core-data.js
  project/data-access-layer/integrated/remove-metadata.js
  project/data-access-layer/standalone/mock-data.js
  project/i-on-web-server.js
Labels: refactor, review

#71 Review before delivery
  project/__tests__/test-i-on-web.js
  project/business-logic-layer/i-on-web-services.js
  project/data-access-layer/integrated/core-add-missing-data.js
  project/data-access-layer/integrated/core-cache.js
  project/data-access-layer/integrated/core-data-transformer.js
  project/data-access-layer/integrated/core-data.js
  project/data-access-layer/integrated/remove-metadata.js
  project/data-access-layer/standalone/mock-data.js
  project/i-on-web-server.js
  project/presentation-layer/i-on-web-ui.js
  project/test/test-services.js
  project/views/class-sections.hbs
  project/views/layout.hbs
  project/views/programmeOffers.hbs
  project/views/user-calendar.hbs
  project/views/user-classes.hbs
Labels: review

#75 Small fixes
  .docker/docker-compose-heroku.yml
  .docker/docker-compose.yml
  README.md
  docs/i-on Web Relatorio Final.pdf
  docs/i-on Web Relatorio Intercalar.pdf
  docs/i-on Web Relatório Inicial.pdf
  project/i-on-web-server.js
Labels: documentation

#76 Standalone/add mock data
  project/i-on-web-server.js
  project/mock-data/standalone/calendarTerms/2020-2021-2/21/class.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/21/classSections/LEIRT61D.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/21/classSections/LI61D.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/21/classSections/LI61N.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/21/events.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/31/class.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/31/classSections/LEIRT61D.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/31/classSections/LI61D.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/31/events.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/42/class.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/42/classSections/LEIRT61D.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/42/classSections/LI61D.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/42/classSections/LI61N.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/42/events.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/46/class.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/46/classSections/LEIRT41D.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/46/classSections/LI61N.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/46/events.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/50/class.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/50/classSections/LEIRT21D.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/50/events.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/68/class.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/68/classSections/LEIRT61D.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/68/events.json
  project/mock-data/standalone/calendarTerms/2020-2021-2/semester_calendar.json
  project/mock-data/standalone/current_calendar_term.json
Labels: standalone mode
